version: '3.3'

services:
   nginx:
      image: nginx
      restart: always
      ports:
         - 80:8000
         - 443:443
      volumes:
         - ./nginx/conf:/etc/nginx/conf.d
         - ./nginx/data:/data
      secrets:
         - ghost_private
         - ghost_public
      depends_on:
         - ghost

   ghost:
      image: ghost
      restart: always
      expose:
         - ${SERVER_PORT}
      volumes:
         - ./ghost:/var/lib/ghost/content
      environment:
         NODE_ENV: production
         url: ${URL} 
         admin__url: ${URL}
         server__port: ${SERVER_PORT} 
         database__client: ${DB_CLIENT}
         database__connection__host: ${DB_HOST}
         database__connection__user: ${DB_USER}
         database__connection__password: ${DB_PASS}
         mail__transport: "SMTP"
         mail__options__service: "Gmail"
         mail__options__auth__user: ${MAIL_USER}
         mail__options__auth__pass: ${MAIL_PASS}
      depends_on:
         - db

   db:
      image: hypriot/rpi-mysql
      restart: always
      volumes:
         - ./mysql:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: ${DB_PASS} 

secrets:
   ghost_private:
      file: ./keys/ghost.private
   ghost_public:
      file: ./keys/ghost.public
